language: csharp
sudo: false
env:
  global:
  - PACKAGE_NAME=compat-${TRAVIS_BUILD_NUMBER}
  - ARTIFACTS_KEY=AKIAIJ6RNS2NO5AJFEWA
  - secure: Xl6yiQYNQQvWk1HLKqazeT+KMQLWx5SJ1Gw3uq5px+/iVSnVgZNEvdXFeFv66DJ6by7vqRm7FcOa2w91a0U+8RkYnpeJHgp6i4StU/+SOGcZzw/beUzyWNqe6wJCEF80tRo5LeKpqZFMGfqA9rkk2JVxjeho36uTnADNIh9FHdYMsiTSZdqV5wCZVIRU21Ewlt33yCHE/kdICS/pTuY0lOBUSfrdcB7OMIr+ay1tJrVIwkSoqJzD4J+2eq+3pcyUwXgNv03ZdPw3LmQEbKkT86Mk0Sg4s0Lq5xTfZY7KpT5Xcxa+BlE5Ikx50EATqXDOBzU8iedB3Nl46LLmzeeNl7X/nSZegSjO+Jl/OrYHZS3vqLTI+lyVbl6o2Ia8LDubL2Qb4cwjBWthewX2GPpC5py9l+eras+Ousb64T8w4tYYH5d6/YqtBmtHIa3PdPnuNQ03Db/iOmQEQgtO4+eH2OQ5udPZ/Qx6gpgP6S1wLv4zySt9wr2TT05h7UpR4X1GM7Zi3qCovB10274fNkfrKLvRu8Bwq2Qc7kuYKKaUR/U7ofEKvrJDMhm3u0CS2dp5XAePaUdQh6r0TPnSeMYHorTGt03P+i4JiAs9Kz9F9RPFE7vU+DMQ4dEBwTf5E9jBsEONvCKJDpFN1XUQjOjMd9Db4oLLzDBhvzQAYJId6dc=
  - ARTIFACTS_S3_BUCKET=erdos
  - ARTIFACTS_S3_REGION=eu-west-1
  - ARTIFACTS_PERMISSIONS=public-read
  - ARTIFACTS_TARGET_PATHS=builds/compat
  - VERSION_FILE=src/Compat/Resources/Version.txt
solution: src/Compat.sln
script: script/cibuild
before_script: echo -n "$(cat ${VERSION_FILE})+${TRAVIS_BUILD_NUMBER} (git ${TRAVIS_COMMIT:0:7}; $(date -u))" > $VERSION_FILE
after_success:
- if [[ "$TRAVIS_TAG" != "" ]]; then export PACKAGE_NAME=compat-${TRAVIS_TAG}; fi
- zip -j ${PACKAGE_NAME}.zip bin/Release/{Compat.exe,Mono.Cecil.dll} LICENSE
- curl -sL https://raw.githubusercontent.com/travis-ci/artifacts/master/install | bash
- artifacts upload ${PACKAGE_NAME}.zip
deploy:
- provider: releases
  api_key:
    secure: "btONi7rcPAqaxYkihAe/cj37ZWIle8ZzVt1im74fAXsSfOwEfBuJ8rn4hyOQ6fQ82Myy2/teWUXRHL8gyzOspq1A5+CwF2sbQvkW3MtXjI+rbbfnVyaDnDtUPcAXgqMeDTjZTV6yfFn6yYr6YY7AWdv5+zZCOT/hzTnasjlvYfzRnEKr0vNry4jGrdduxmHeLscQzSTrqitgB20pbRLYk1wxXSXb4oqL4WEvYaFKuJvk3tSSUjayZow5vAv1J4FcGTXssdReRy4zW7kN7TaCMoBG8mM8vbk9rDLkK5Vt5dNl9/x0kEknDPxPuGitJoty6kvQ5Z68NVhwrSJZ7rD62mvh5ocWIX9PUnrY3igRlYo3PcQuiv4DoeO6d/KFVs7Q/8R9NmJ8+67v/IsZHgdjk6x6k6QNdfCa3hatXzSI2brnqgaYP6ls33Q1YteKOpc4vMp+xBOb5PKZ7L8da9p9eU6M4JqmFUnPDmjfV0dj8mIP7DxjHoDsXKcEa/cnJxeLLFgn/JHGwl/wngTWUWpmvDYbjVY4WE7UCZJFNqPl9UEfcjanG/0SnGz4X4XvVrONsm+rK6L6DZcL0C05DTz7uusWhjnkKSNWjSFbn44um+bCOgAGdHXd88KZ6GGsXEmg0o9Njmdr83C6u/ZzPbt6+zlI5+ZFjwi0Y3XfJ5oRYRc="
  file: ${PACKAGE_NAME}.zip
  skip_cleanup: true
  on:
    tags: true
