language: csharp
sudo: false
env:
  global:
  - PACKAGE_NAME=compat-${TRAVIS_BUILD_NUMBER}
  - ARTIFACTS_KEY=AKIAIJ6RNS2NO5AJFEWA
  - secure: Xl6yiQYNQQvWk1HLKqazeT+KMQLWx5SJ1Gw3uq5px+/iVSnVgZNEvdXFeFv66DJ6by7vqRm7FcOa2w91a0U+8RkYnpeJHgp6i4StU/+SOGcZzw/beUzyWNqe6wJCEF80tRo5LeKpqZFMGfqA9rkk2JVxjeho36uTnADNIh9FHdYMsiTSZdqV5wCZVIRU21Ewlt33yCHE/kdICS/pTuY0lOBUSfrdcB7OMIr+ay1tJrVIwkSoqJzD4J+2eq+3pcyUwXgNv03ZdPw3LmQEbKkT86Mk0Sg4s0Lq5xTfZY7KpT5Xcxa+BlE5Ikx50EATqXDOBzU8iedB3Nl46LLmzeeNl7X/nSZegSjO+Jl/OrYHZS3vqLTI+lyVbl6o2Ia8LDubL2Qb4cwjBWthewX2GPpC5py9l+eras+Ousb64T8w4tYYH5d6/YqtBmtHIa3PdPnuNQ03Db/iOmQEQgtO4+eH2OQ5udPZ/Qx6gpgP6S1wLv4zySt9wr2TT05h7UpR4X1GM7Zi3qCovB10274fNkfrKLvRu8Bwq2Qc7kuYKKaUR/U7ofEKvrJDMhm3u0CS2dp5XAePaUdQh6r0TPnSeMYHorTGt03P+i4JiAs9Kz9F9RPFE7vU+DMQ4dEBwTf5E9jBsEONvCKJDpFN1XUQjOjMd9Db4oLLzDBhvzQAYJId6dc=
  - ARTIFACTS_S3_BUCKET=erdos
  - ARTIFACTS_S3_REGION=eu-west-1
  - ARTIFACTS_PERMISSIONS=public-read
  - ARTIFACTS_TARGET_PATHS=builds/compat
  - VERSION_FILE=src/Compat/Resources/Version.txt
solution: src/Compat.sln
script: script/cibuild
before_script: echo -n "$(cat ${VERSION_FILE})+${TRAVIS_BUILD_NUMBER} (git ${TRAVIS_COMMIT:0:7}; $(date -u))" > $VERSION_FILE
after_success:
- if [[ "$TRAVIS_TAG" != "" ]]; then export PACKAGE_NAME=compat-${TRAVIS_TAG}; fi
- zip -j ${PACKAGE_NAME}.zip bin/Release/{Compat.exe,Mono.Cecil.dll} LICENSE
- curl -sL https://raw.githubusercontent.com/travis-ci/artifacts/master/install | bash
- artifacts upload ${PACKAGE_NAME}.zip
deploy:
- provider: releases
  api_key:
    secure: IW+13s6yAJxUT+CHRUAAImFiwtugEpEHo5guY9JrxOkLpqS8OJNtesGqu+RULVjsBF0Al0KxgBucsFROdXZraXTZJzBQFQIa1d8lFFhKexLUtWggupPYbDUyUSzxYMJoiqL1+uhbS82c8b/akpKOKmbyv+331Ic2+TCj94p5+UKAusppCjwAx6ZlsUoh3CXZlqCldJJ/7PmLIvr3oTJEZMKQqHeqcHiIo/viHKYD0xIDMNYPCqL4UDKaMlixX7BVc8xsx88Y07DINnxieD/JT/JQLo5ra2MlawBg4A/tOOMdAwhnwvWzwAq3sj5htL+1Yh92rN4I71lOGGX/nr9RHRJh09tiN00gwUB0mk6xA1MbgFdCjRFyCMZK0PXsKJKiHTvQuHCKc7Hd/EZ6aqxeiLpnIh9yop/ywSLMM7dFWS3a/Io0GbK3JdrX3h/PkrklFu/BKYKROX9va7wNI2otgKbPO40N0diLap7TV+TOaTlOUhPQHAYggC2gXCGSDj8hMqxMEjm++0xFO6m8bMokX/LD+mLg2yrAz25Vr5xtx4db4UHObcx2QvHccz6hoAuimag0rtNucyEoG2CJj9kgBCSUbijuFKhlXzbXCRnUiwzfRm4zXsiGFW1opL5dNVB9og4n3E7CjXd/iXvcmopVQUfxg6eeRXQp/gaDNnlBr9c=
  file: ${PACKAGE_NAME}.zip
  skip_cleanup: true
  on:
    tags: true
